# File: .github/workflows/firebase-deploy.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # change if your main branch is named differently

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVOPS_TEAM04 }}'
          channelId: live
          projectId: devops-team04
